- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: my_aws_key
    key_path: "{{ lookup('env', 'HOME') }}/.ssh/{{ key_name }}.pub"
    region: us-west-2
    sec_group_master: jenkins
    id_master: jenkins
    image: ami-0d1cd67c26f5fca19
    instance_type: t2.medium
    vpc_subnet: subnet-967099ee
    hosts_path: hosts

  tasks:
    - name: Provision EC2 instances
      block:

      - name: Upload public key to AWS
        ec2_key:
          name: "{{ key_name }}"
          key_material: "{{ lookup('file', key_path ) }}"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"

      - name: Create security group
        ec2_group:
          name: "{{ sec_group_master }}"
          description: "Sec group for control-plane nodes"
          region: "{{ region }}"
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          rules:
            - proto: tcp
              ports: 22
              cidr_ip: 0.0.0.0/0
              rule_desc: allow all on ssh port

            - proto: tcp
              ports: 8080
              cidr_ip: 0.0.0.0/0
              rule_desc: access port

        register: result_sec_group_master

      - name: Provision a jenkins server instance
        ec2:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          key_name: "{{ key_name }}"
          group_id: "{{ result_sec_group_master.group_id }}"
          image: "{{ image }}"
          instance_type: "{{ instance_type }}"
          region: "{{ region }}"
          vpc_subnet_id: "{{ vpc_subnet }}"
          assign_public_ip: yes
          # id: "{{ id_master }}"
          instance_tags:
            Name: "{{ id_master }}"
          wait: true
          count: 1
